# Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_pedidos_jpa
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# Logging
logging:
  level:
    br:
      com:
        carloseduscc:
          projetoestudos: debug

# Doc
springdoc:
  override-with-generic-response: false